export const candidates = [
  {
    _id: '5d0feacff3cdb49b9d53f188',
    index: 0,
    isActive: false,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Adriana',
      last: 'Odonnell'
    },
    red_stars: 3,
    orange_stars: 42,
    yellow_stars: 41,
    company: 'CORMORAN',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'adriana.odonnell@cormoran.name',
    phone: '+1 (854) 595-3564',
    address: '700 Oriental Court, Rockingham, West Virginia, 7136',
    short_description:
      'Aute do nulla consequat aliqua sint ex aliquip qui quis adipisicing cillum sunt aliquip sint. Officia anim nostrud nulla tempor qui excepteur do cillum occaecat proident ut. Eiusmod ea voluptate commodo esse labore veniam anim eiusmod culpa velit. Lorem ex velit incididunt esse enim irure.',
    registered: 'Thursday, July 20, 2017 3:35 AM',
    last_login: 'Saturday, April 27, 2019 8:05 PM',
    latitude: '4.192739',
    longitude: '11.95201',
    languages: ['java', 'c'],
    technologies: ['eu', 'sunt', 'exercitation', 'esse', 'id']
  },
  {
    _id: '5d0feacf0d8c2045139a89b0',
    index: 1,
    isActive: false,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Rivers',
      last: 'Hoffman'
    },
    red_stars: 21,
    orange_stars: 49,
    yellow_stars: 44,
    company: 'HOMELUX',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'rivers.hoffman@homelux.tv',
    phone: '+1 (969) 435-3149',
    address: '829 Holly Street, Babb, Indiana, 635',
    short_description:
      'Aute amet laborum excepteur non esse minim ad irure. Ea ullamco anim est labore nulla aliqua pariatur reprehenderit excepteur reprehenderit. Fugiat aute sint in Lorem cillum ex eiusmod aliqua anim. Enim enim labore veniam magna eu deserunt aliquip.',
    registered: 'Wednesday, January 15, 2014 5:30 AM',
    last_login: 'Friday, March 14, 2014 3:20 PM',
    latitude: '59.770867',
    longitude: '100.329937',
    languages: ['c', 'swift'],
    technologies: ['duis', 'eu', 'adipisicing', 'nisi', 'cupidatat']
  },
  {
    _id: '5d0fead07979ccc1b95e7857',
    index: 2,
    isActive: true,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Jones',
      last: 'Blair'
    },
    red_stars: 78,
    orange_stars: 92,
    yellow_stars: 92,
    company: 'FLEXIGEN',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'jones.blair@flexigen.io',
    phone: '+1 (988) 549-3297',
    address: '929 Herkimer Court, Joppa, Hawaii, 6121',
    short_description:
      'Ut elit Lorem deserunt irure aute deserunt esse ex culpa enim excepteur cupidatat ullamco ullamco. Sint ipsum laboris reprehenderit id est commodo. Ut irure dolore officia excepteur. Irure aute dolore duis nulla esse proident enim velit consectetur. Aute Lorem incididunt culpa qui aliqua esse reprehenderit dolore. Aliqua laboris aute cillum ad fugiat deserunt. Non duis in magna ea nisi sit consectetur aliquip cillum.',
    registered: 'Friday, January 5, 2018 7:35 AM',
    last_login: 'Saturday, May 13, 2017 12:53 PM',
    latitude: '-57.32066',
    longitude: '-144.885054',
    languages: ['kotlin', 'java', 'ruby'],
    technologies: ['nostrud', 'consequat', 'sit', 'enim', 'id']
  },
  {
    _id: '5d0fead069da453338b1180a',
    index: 3,
    isActive: true,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Katherine',
      last: 'Morrow'
    },
    red_stars: 68,
    orange_stars: 46,
    yellow_stars: 1,
    company: 'MOTOVATE',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'katherine.morrow@motovate.me',
    phone: '+1 (975) 584-2215',
    address: '997 Hewes Street, Hall, Alabama, 3412',
    short_description:
      'Nostrud quis consectetur elit quis veniam qui excepteur enim elit ea nulla nostrud sint. Esse labore enim incididunt nulla ipsum eu consequat sint cupidatat consectetur. Commodo culpa ullamco mollit et mollit nostrud irure anim qui. Ea Lorem excepteur quis do exercitation minim pariatur id est exercitation. Sint exercitation incididunt esse ut id enim sint commodo quis. Veniam minim laboris id velit amet dolor dolore excepteur laboris. Amet ad non ex eiusmod aute elit consectetur elit sint occaecat aliqua commodo anim.',
    registered: 'Thursday, May 24, 2018 12:08 PM',
    last_login: 'Saturday, July 15, 2017 6:50 AM',
    latitude: '18.180876',
    longitude: '43.343584',
    languages: ['kotlin', 'rust', 'c'],
    technologies: ['ea', 'et', 'incididunt', 'dolor', 'officia']
  },
  {
    _id: '5d0fead0219570c8a76b9885',
    index: 4,
    isActive: false,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Virginia',
      last: 'Roberson'
    },
    red_stars: 75,
    orange_stars: 72,
    yellow_stars: 95,
    company: 'DOGNOST',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'virginia.roberson@dognost.info',
    phone: '+1 (915) 467-2876',
    address: '409 Kensington Street, Guthrie, Maryland, 2005',
    short_description:
      'Labore deserunt consectetur tempor occaecat voluptate veniam laborum irure voluptate adipisicing elit qui magna. Id duis minim in adipisicing id consectetur duis. Elit aliqua ipsum laborum cupidatat incididunt. Laboris minim amet commodo cillum. Eiusmod veniam duis culpa aliquip reprehenderit aute veniam. Non fugiat commodo sint tempor qui in ut ex elit amet. Reprehenderit culpa sunt labore dolor commodo excepteur tempor id eu veniam incididunt aliquip id.',
    registered: 'Saturday, October 1, 2016 1:57 AM',
    last_login: 'Saturday, December 3, 2016 10:08 PM',
    latitude: '-40.37105',
    longitude: '9.483465',
    languages: ['ruby', 'javascript', 'java'],
    technologies: ['do', 'sit', 'dolor', 'in', 'reprehenderit']
  },
  {
    _id: '5d0fead004a2bb065c6ce1c1',
    index: 5,
    isActive: false,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Katheryn',
      last: 'Pittman'
    },
    red_stars: 72,
    orange_stars: 74,
    yellow_stars: 39,
    company: 'BISBA',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'katheryn.pittman@bisba.com',
    phone: '+1 (929) 599-3403',
    address: '456 Nevins Street, Lowgap, Kentucky, 1278',
    short_description:
      'Pariatur velit cillum ad eu anim aute. Ut eu velit ea adipisicing elit ipsum sit irure cupidatat ut eu. Aute nisi culpa pariatur anim ea occaecat adipisicing pariatur nisi adipisicing et.',
    registered: 'Wednesday, February 4, 2015 11:09 AM',
    last_login: 'Monday, March 26, 2018 1:50 PM',
    latitude: '-19.883306',
    longitude: '179.830855',
    languages: ['java', 'c++'],
    technologies: ['esse', 'ex', 'aliquip', 'incididunt', 'incididunt']
  },
  {
    _id: '5d0fead0729e92cd6e9af99f',
    index: 6,
    isActive: true,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Nellie',
      last: 'Reid'
    },
    red_stars: 66,
    orange_stars: 72,
    yellow_stars: 88,
    company: 'GINK',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'nellie.reid@gink.ca',
    phone: '+1 (836) 504-3019',
    address: '650 Roosevelt Court, Statenville, Palau, 6144',
    short_description:
      'Id nisi ad nulla elit ut culpa ullamco. Reprehenderit consequat ea dolore nostrud sunt mollit. Pariatur laboris in aliqua ex nisi.',
    registered: 'Monday, October 2, 2017 1:11 AM',
    last_login: 'Tuesday, July 24, 2018 3:23 PM',
    latitude: '-2.923258',
    longitude: '90.984368',
    languages: ['kotlin', 'c'],
    technologies: ['nostrud', 'magna', 'nostrud', 'aute', 'ea']
  },
  {
    _id: '5d0fead0f8b43b0644280b07',
    index: 7,
    isActive: false,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Estrada',
      last: 'Levy'
    },
    red_stars: 15,
    orange_stars: 39,
    yellow_stars: 43,
    company: 'PHEAST',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'estrada.levy@pheast.us',
    phone: '+1 (831) 468-3122',
    address: '873 Cherry Street, Concho, Nebraska, 9183',
    short_description:
      'Sint laboris id id fugiat nulla deserunt. Ut cillum nostrud culpa ex minim reprehenderit tempor id sunt sit. Incididunt in ad voluptate eiusmod Lorem excepteur aute. Enim tempor id do laborum eiusmod non. Sunt voluptate veniam in duis sunt irure ipsum non quis id ipsum.',
    registered: 'Wednesday, December 31, 2014 9:37 AM',
    last_login: 'Monday, November 10, 2014 5:47 AM',
    latitude: '5.439403',
    longitude: '-83.917645',
    languages: ['c++', 'swift', 'kotlin'],
    technologies: ['nostrud', 'nulla', 'reprehenderit', 'ut', 'sunt']
  },
  {
    _id: '5d0fead0a6a2816c207db4aa',
    index: 8,
    isActive: true,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Sanders',
      last: 'Juarez'
    },
    red_stars: 73,
    orange_stars: 85,
    yellow_stars: 23,
    company: 'HOUSEDOWN',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'sanders.juarez@housedown.biz',
    phone: '+1 (820) 586-3512',
    address: '748 Degraw Street, Albany, Illinois, 8947',
    short_description:
      'Laboris magna minim ad nulla laborum. Ipsum excepteur id et esse in sit. Culpa exercitation ut cupidatat ullamco proident laborum aliquip nostrud in ea deserunt ad sit reprehenderit.',
    registered: 'Monday, October 17, 2016 7:27 PM',
    last_login: 'Monday, December 25, 2017 3:59 PM',
    latitude: '-81.121779',
    longitude: '68.301127',
    languages: ['kotlin', 'java', 'ruby'],
    technologies: ['excepteur', 'enim', 'exercitation', 'ex', 'ut']
  },
  {
    _id: '5d0fead09501a8b9813afd6b',
    index: 9,
    isActive: true,
    picture: 'http://placehold.it/32x32',
    name: {
      first: 'Corine',
      last: 'Pena'
    },
    red_stars: 9,
    orange_stars: 96,
    yellow_stars: 57,
    company: 'XPLOR',
    linkedin: 'https://www.linkedin.com/in/sshetty2/',
    github: 'https://github.com/Sshetty2',
    portfolio: 'https://www.sshetty2.com/',
    email: 'corine.pena@xplor.org',
    phone: '+1 (840) 580-3476',
    address: '641 Whitty Lane, Callaghan, Oregon, 7087',
    short_description:
      'Adipisicing reprehenderit occaecat veniam sit non elit in incididunt eiusmod nulla duis. Aliqua amet incididunt ut enim excepteur culpa veniam proident aute deserunt do enim. Do qui est laborum amet irure ullamco aliquip. Occaecat exercitation labore incididunt pariatur nulla est nisi dolore mollit. Elit nostrud nulla tempor et aute sit fugiat Lorem laboris nisi est. Et magna laboris quis deserunt culpa ipsum ad sunt eiusmod mollit ipsum velit fugiat.',
    registered: 'Monday, October 19, 2015 2:43 AM',
    last_login: 'Thursday, March 19, 2015 11:16 PM',
    latitude: '44.122997',
    longitude: '8.679585',
    languages: ['swift', 'c', 'rust'],
    technologies: ['velit', 'excepteur', 'ad', 'sunt', 'eiusmod']
  }
];
